### ISSUE TITLE
Please do not spam your project.

### ISSUE THREAD

**Issue by amcgregor** [poonai/inspektor#18]
> Hey Alice ZoÃ« BevanâEUR"McGregor

Especially if you can't successfully write my name, incorrectly believe I would be interested, plus the point that this activity may be in violation of GitHub Terms of Service / Acceptable Use Policy. (The e-mail address targeted was harvested from my GitHub profile, and the origin matches your account profile's publicly listed address.)

I typed out something helpful twice, now, only to delete the comments after remembering _I'm responding to spam._

**Comment by poonai** [comment]
Sure @amcgregor . Thought of showcasing it. 

Didn't mean to spam you.
